version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8081:8080"
  backend:
    build:
      context: .
      dockerfile: BillGeneratorApi/Dockerfile
    ports:
      - "5000:80"